# Generated by Django 3.2 on 2022-12-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticia_breve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='breve',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
